# Generated by Django 6.0.1 on 2026-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'permissions': [('exclude_member', 'Peut exclure un membre du salon')]},
        ),
    ]
