# Generated by Django 6.0.1 on 2026-01-20 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='members',
            field=models.ManyToManyField(related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
