# Generated by Django 6.0.1 on 2026-01-22 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_alter_salon_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_from_salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
