# Generated by Django 6.0.1 on 2026-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_salon_message_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='user_role',
            field=models.CharField(choices=[('modo', 'modérateur'), ('adm', 'admin'), ('mem', 'membre')], max_length=50, null=True),
        ),
    ]
